#!/bin/bash

# minify command from https://guide.elm-lang.org/optimization/asset_size.html

elm make src/Main.elm --output=tmp.js --optimize
uglifyjs tmp.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=hexasperate.js

echo "Compiled size: $(cat tmp.js | wc -c) bytes"
echo "Minified size: $(cat hexasperate.js | wc -c) bytes"
echo ""

rm tmp.js

